---

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 23BassSword42
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/types.sql:/docker-entrypoint-initdb.d/types.sql:ro

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 127.0.0.1:3001:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./test/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # run `while true; do ../../runner/run.sh 10.23.42.0/24 & sleep 10s; wait $!; done` in ./test/scan

  scanalyzer:
    build: scanalyzer
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PASSWORD: 23BassSword42

  web:
    build: web
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:80

volumes:
  grafana-data:
