---

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 23BassSword42
    volumes:
      - ./types.sql:/docker-entrypoint-initdb.d/types.sql:ro

  runner:
    build: runner
    restart: unless-stopped
#   command:
#     - 127.0.0.1/32
    volumes:
      - scan-data:/scan

  scanalyzer:
    build: scanalyzer
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PASSWORD: 23BassSword42
    volumes:
      - scan-data:/scan

  web:
    build: web
    restart: unless-stopped

volumes:
  scan-data:
